### ISSUE TITLE
Do I need the Joomla database?

### ISSUE THREAD

**Issue by astridx** [joomlatools/joomlatools-pages#284]
I just looked at this component. Thank you for sharing.

Which is not quite clear to me yet. You write that you don't need a database. But you need the Joomla database, it's just that the articles are not stored in the database, right?

Then I have a small comment about this wiki page: https://github.com/joomlatools/joomlatools-pages/wiki/Getting-Started. I stumbled across the term `In the root folder of your Joomla installation, create the following folder structure: joomlatools-pages ...`
 .
At first I thought that I should create a directory called `joomlatools-pages`. When considering carefully, it is clear that the front end directory of the component is meant. But you can also write that directly. For example: `In the site part of the component folder of your Joomla installation /components/com_pages, use the following folder structure: pages ….`

**Comment by johanjanssens** [comment]
@astridx Thanks for the feedback, can you please use our chat or our forums for questions. The Github issues are only intended for PR's. 

- chat: https://gitter.im/joomlatools/dev
- mailing list: https://groups.google.com/forum/#!forum/joomlatools-dev

Most happy to further assist you from there, thanks for understanding.

**Comment by astridx** [comment]
See https://groups.google.com/forum/#!topic/joomlatools-dev/9fNbWe0HQOw
