### ISSUE TITLE
date('Y') does not yeild properly

### ISSUE THREAD

**Issue by itsromack** [joomlatools/joomlatools-pages#318]
### test.html.php
`<?php echo 'foo ' . date('Y');?>`

### Output
`foo 20 April 2020`

### Expected Output
`foo 2020`

**Comment by johanjanssens** [comment]
The date template method accepts a date as first argument and a format as second argument. The following works

`<?= date('now', 'Y') ?>`

The code be found here: https://github.com/joomlatools/joomlatools-pages/blob/master/code/site/components/com_pages/template/default.php#L217

This method has not been documented yet, it should be documented here: https://github.com/joomlatools/joomlatools-pages/wiki/Functions#date

Your help would be appreciated.

For questions like this please use our chat, or forum and not the Github issues. Thanks!
