### ISSUE TITLE
Tailwind theme

### ISSUE THREAD

**Issue by waseemsadiq** [joomlatools/joomlatools-pages#385]
Build a base theme, see: https://tailwindcss.com/ and https://preset-env.cssdb.org/features

### Resouces:

- https://pawelgrzybek.com/from-sass-to-postcss/
- https://www.toptal.com/front-end/postcss-sass-new-play-date
- https://dev.to/michaeldscherr/switching-from-sass-to-postcss-4p0c

**Comment by johanjanssens** [comment]
@waseemsadiq A good theme to base ourselves on could be the default Wordpress theme: https://make.wordpress.org/core/2020/10/22/twenty-twenty-one-dark-mode-discussion/

**Comment by johanjanssens** [comment]
Possible name for a base theme could be `frontcover`
