### ISSUE TITLE
Possible conflict with platform 

### ISSUE THREAD

**Issue by yiendos** [joomlatools/joomlatools-pages#456]
Platform and pages no longer seems to work together, discovered through the testing of various options in relation to: 
https://github.com/joomlatools/joomlatools-pages-playground/pull/6

#### Steps to reproduce the behavior

1. `joomla site:create platform --repo=https://github.com/joomlatools/joomlatools-platform.git`
2. `composer require joomlatools/pages --working-dir=/var/www/platform --ignore-platform-reqs`
3. Visit `http://platform.test` in the browser

#### Expected result 

Site renders correctly

#### Actual result

```
KExceptionError | Fatal Error [500]
Class 'JError' not found
.../app/site/components/com_pages/event/subscriber/errorhandler.php:15
10 class ComPagesEventSubscriberErrorhandler extends ComPagesEventSubscriberAbstract
11 {
12     public function onAfterKoowaBootstrap(KEventInterface $event)
13     {
14         //Catch all Joomla exceptions
15         JError::setErrorHandling(E_ERROR, 'callback', array($this, 'handleException'));
16     }
17 
18     public function onException(KEventException $event)
19     {
20         if($this->getObject('request')->getFormat() == 'html')
KExceptionHandlerAbstract->_handleException()
{PHP internal call}
```

**Comment by johanjanssens** [comment]
@yiendos Good find, i need to add a check here, platform doesn't use JError anymore it uses exceptions everywhere so this code isn't required there. A simple conditional check will do the trick.
