### ISSUE TITLE
Install fails J3.9.3, PHP 7.2.11

### ISSUE THREAD

**Issue by Bodge-IT** [joomlatools/joomlatools-pages#524]
Please describe the expected and actual behavior.
1.  Install pages 0.19.3 ...installs but breaks site....diff issue.
2.  Install pages 0.19.4  Fails with error "Installation Failed" on Joomlatools framework install, before pages install is attempted.

#### Steps to reproduce the behavior

1.  Installing 0.19.4 through extension install package file option
2.  Install pages 0.19.4  Fails with error "Installation Failed" on Joomlatools framework install, before Pages install is attempted(ie doesn't get to Pages status).

#### Testing instructions

1. - [ ] Testing install on localhost XAMPP on loaded site running J3.9.3, PHP 7.2.11.
2. - [ ] Pages 0.19.3 does install on this system.

#### Support tickets

* _

**Comment by johanjanssens** [comment]
@Bodge-IT For  issues with installations please use our community resources and not the issue tracker. Often these kind of issues are easily resolved. For more info how to reach us: https://github.com/joomlatools/joomlatools-pages/wiki/Community

**Comment by Bodge-IT** [comment]
Hey Johan, wasn't looking for support just informing you of issues with the installer.

⁣Thumbed on the run

Sent from BlueMail ​


-------- Original Message --------

**Comment by johanjanssens** [comment]
Thanks, much appreciated. I double checked the installer for you and it is working fine. The installer is the same installer we use for all our Joomlatools extensions if there would be an issue with it, we would have received multiple reports. Usually this is a local problem.

There is a small routing issue in 0.19.3, that is fixed for 0.19.4 but there is still a small problem that remains when SEF is disabled which i'm resolving now. Will all be fixed for 0.19.5. 

In future please use the chat or the mailing list for these kind of issues, makes communication easier and doesn't give unneeded notifications to people watching all repo activity.

**Comment by johanjanssens** [comment]
@Bodge-IT I have released 0.19.5 for which fixes the SEF issues. I cannot replicate any installer problems, if you still have issues installing please jump into the Gitter chat https://gitter.im/joomlatools/dev and happy to assist you from there.
