### ISSUE TITLE
Accessing frontmatter built-in vars in a page

### ISSUE THREAD

**Issue by sakiss** [joomlatools/joomlatools-pages#542]
I am trying to read and print the frontmatter vars as per the [documentation](https://github.com/joomlatools/joomlatools-pages/wiki/Page) using the `$[property]` with no success. Tried both in an html and an html.php page. Not sure if this is a php var or something like Jekylls liquid vars.

#### Steps to reproduce the behavior
page code:
```
---
title: My Name
summary: A super duper summary for this page.
myName: Sakis
---

<h3>My name is somename1</h3>
<p>Welcome to my new page.</p>
<span>$[title]</span>
```
results in:
![My_Name](https://user-images.githubusercontent.com/1838041/107978852-29c64700-6fc6-11eb-9044-20d8e0234454.png)

**Comment by johanjanssens** [comment]
Hello Sakiss, happy to help you, but please do not use the issue tracker to ask questions. The issue tracker is for development only.

For questions please use our community resources. Please see: https://github.com/joomlatools/joomlatools-pages/wiki/Community#where-to-get-support

As for your question, anywhere the docs use [...] you need to fill in the proper variable name and remove the [ ] so in your case it would be `$title` not `$[title]`Please also make sure that you are using the php engine for your page as explained here: https://github.com/joomlatools/joomlatools-pages/wiki/Templates#engines or it will be treated as just text.
