### ISSUE TITLE
Wiki Configuration sample issues

### ISSUE THREAD

**Issue by sakiss** [joomlatools/joomlatools-pages#552]
Please describe the expected and actual behavior.

The issue references the wiki page: https://github.com/joomlatools/joomlatools-pages/wiki/Configuration

The sample configuration has both syntax and runtime errors.
1. DEBUG is undefined. Plz use JDEBUG
2. Missing comas at the end of the array

**Comment by johanjanssens** [comment]
Hello Sakis, please, pretty please do not use the issues for this. I know that this is the case in most Github repo's but with the new discussions functionality that Github has added issues should really only be related to code changes. 

For questions, ideas, etc you can always get in touch through: ihttps://github.com/joomlatools/joomlatools-pages/discussions/categories/general as an example: https://github.com/joomlatools/joomlatools-pages/discussions/545

About the wiki. The wiki open to be edited by anyone, feel free to make edits where needed, if you are not sure about them, or need feedback, just open up a discussion for wiki edits and happy to help you.
