### ISSUE TITLE
Prepare 0.1 release

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-pages#7]
- [x] Finish testing and merging
- [x] Update version info
- [x] Register on packagist

Note: this release requires joomlatools/joomlatools-framework#152

**Comment by johanjanssens** [comment]
@stevenrombauts Can you register this repo on packagist?

**Comment by stevenrombauts** [comment]
@johanjanssens The repository has been registered, but installing fails. Paul also confirmed this. Seems to be some Composer bug where it is comparing incorrect PHP versions, but will have to investigate further this week.

**Comment by johanjanssens** [comment]
@stevenrombauts No problem, anything we can do on our end?

**Comment by johanjanssens** [comment]
@stevenrombauts Thanks for the info.

1. Lets not complicate this, I have added instructions to the readme to include the --ignore-platform-reqs flag when installing with composer. 

2. Good catch. This is because the legacy libs are not loaded. This is being resolved here: https://github.com/joomlatools/joomlatools-framework/pull/159

3. Oki, suggest we do a maintenance release of the vagrant box to resolve this asap?

**Comment by johanjanssens** [comment]
@ercanozkaya Can you try to build a package including the framework? i would like to have this easily installable. Please also check if all the info is there for the 0.1.0 release
